name: Main Tests Pipeline

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 2 * * *' # run daily at 02:00 am (UTC)

jobs:
  build:
    runs-on: ubuntu-20.04
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download and build Zephyr
        id: build
        run: |
          git clone https://github.com/antmicro/qpc.git -b v6.9.3 qpc
          git clone https://github.com/antmicro/qpc-zephyr-port.git
          west init -l qpc-zephyr-port --mf apps/blinky/west.yml
          west update
          west zephyr-export
          export ZEPHYR_BASE=$PWD/zephyr
          export ZEPHYR_TOOLCHAIN_VARIANT=zephyr
          export QPC_PATH=$PWD/qpc
          cd qpc-zephyr-port/apps
          cd hello
          west build -b nrf52840dk_nrf52840 -s app
          echo "::set-output name=zephyr_elf_hello::$PWD/build/zephyr/zephyr.elf"
          cd ..
          cd blinky
          west build -b nrf52840dk_nrf52840 -s app
          echo "::set-output name=zephyr_elf_blinky::$PWD/build/zephyr/zephyr.elf"
          cd ..
          cd dpp
          west build -b nrf52840dk_nrf52840 -s app
          echo "::set-output name=zephyr_elf_dpp::$PWD/build/zephyr/zephyr.elf"
      - name: Run tests in Renode
        uses: antmicro/renode-test-action@zephyr-fix
        env:
          ZEPHYR_QPC_HELLO:  ${{ steps.build.outputs.zephyr_elf_hello }}
          ZEPHYR_QPC_BLINKY: ${{ steps.build.outputs.zephyr_elf_blinky }}
          ZEPHYR_QPC_DPP:    ${{ steps.build.outputs.zephyr_elf_dpp }}
        with:
          renode-version: 'latest'
          tests-to-run: 'tests.robot'
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            report.html
            log.html
            robot_output.xml
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: |
          mkdir deploy
          mv report.html robot_output.xml log.html deploy
          touch deploy/.nojekyll
          echo '<head> <meta http-equiv="refresh" content="0; url=report.html" /> </head>' > deploy/index.html
          cd deploy
          git init
          cp ../.git/config ./.git/config
          git add .
          git config --local user.email "push@gha"
          git config --local user.name "GHA"
          git commit -am "update ${{ github.sha }}"
          git push -u origin +HEAD:gh-pages
          rm -rf .git
