name: Main Tests Pipeline

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 2 * * *' # run daily at 02:00 am (UTC)

jobs:
  build:
    runs-on: ubuntu-20.04
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download and build Zephyr
        id: build
        run: |
          git clone https://github.com/antmicro/qpc.git -b zephyr qpc
          west init -l qpc/ --mf ports/zephyr/west.yml
          west update
          west zephyr-export
          export ZEPHYR_BASE=$PWD/zephyr
          export ZEPHYR_TOOLCHAIN_VARIANT=zephyr
          cd qpc/ports/zephyr/
          west build -b nrf52840dk_nrf52840 -s app
          echo "::set-output name=zephyr_elf::$PWD/build/zephyr/zephyr.elf"
      - name: Run tests in Renode
        uses: antmicro/renode-test-action@zephyr-fix
        env:
          ZEPHYR_HELLO: ${{ steps.build.outputs.zephyr_elf }}
        with:
          renode-version: 'latest'
          tests-to-run: 'tests.robot'
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            report.html
            log.html
            robot_output.xml
